# numpy
- 숫자 데이터를 좀 더 쉽고 편리하게 다룰 수 있는 패키지   

- 다차원 배열 자료구조 클래스인 ndarry를 지원하며 벡터와 행렬을 사용하는 선형대수 계산에 주로 사용됨   

- 배열(Array)이란 순서가 있는 같은 타입의 데이터가 저장되는 자료형을 말한다.
- 리스트도 좋은 자료형이지만 넘파이 배열이 구조적으로 속도가 빠르고 메모리를 더 적게 사용한다.
- 모든 요소가 같은 자료형이어야 한다.
- 요소의 개수를 바꿀 수 없다
- 벡터화 연산을 이용해 간단한 코드로 복잡한 연산을 수행할 수 있다.
- 배열 인덱싱을 사용한 쿼리 기능을 이용해 복잡한 수식을 계산할 수 있다.

In [4]:
!conda list

# packages in environment at /Users/kangjik/opt/anaconda3:
#
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0            py39hecd8cb5_1  
alabaster                 0.7.12             pyhd3eb1b0_0  
anaconda                  2022.10                  py39_0  
anaconda-client           1.11.0           py39hecd8cb5_0  
anaconda-navigator        2.3.1            py39hecd8cb5_0  
anaconda-project          0.11.1           py39hecd8cb5_0  
anyio                     3.5.0            py39hecd8cb5_0  
appdirs                   1.4.4              pyhd3eb1b0_0  
applaunchservices         0.3.0            py39hecd8cb5_0  
appnope                   0.1.2           py39hecd8cb5_1001  
appscript                 1.1.2            py39h9ed2024_0  
argon2-cffi               21.3.0             pyhd3eb1b0_0  
argon2-cffi-bindings      21.2.0           py39hca72f7f_0  
arrow                     1.2.2              pyhd3eb1b0_0  
astroid                   2.11

In [1]:
import numpy as np

- ndarray는 N-dimensional Array의 약자
- np.array(시퀀스 자료형, 주로 튜플보단 리스트를 활용)
- .shape를 사용해 ndarray의 모양을 확인할 수 있다.

In [2]:
ar = np.array([_ for _ in range(10)])
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
ar.shape

(10,)

In [5]:
type(ar)

numpy.ndarray

In [6]:
ar2 = np.array([0.1, 5, 4, 12, 0.5])
ar2

array([ 0.1,  5. ,  4. , 12. ,  0.5])

dtype 속성을 통해 자료형 확인 가능

In [7]:
ar.dtype

dtype('int64')

In [8]:
ar2.dtype

dtype('float64')

- dtype 명시 가능

In [14]:
ar3 = np.array([_ for _ in range(3, 10, 3)], 'i8')
print(ar3)
ar3.dtype

[3 6 9]


dtype('int64')

In [16]:
ar4 = np.array([_ for _ in range(2, 9, 2)], 'f8')
print(ar4)
ar4.dtype

[2. 4. 6. 8.]


dtype('float64')

In [18]:
# 'U8' 유니코드 8글자 자료형을 명시적으로 선언
ar5 = np.array(['가나다라마', '바사아', '자', '차카'], 'U8')
print(ar5)
ar5.dtype
# <U8은 최대 8글자의 유니코드 자료형이다.

['가나다라마' '바사아' '자' '차카']


dtype('<U8')

- 벡터화 연산
    - 배열의 각 요소에 대한 반복 연산을 하나의 명령어로 처리하는 것
    - 비교 연산과 논리 연산을 포함한 모든 종류의 수학 연산에 대해 적용
     

In [20]:
x = np.array([_ for _ in range(10)])
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
2 * x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [22]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

In [23]:
2 * a + b

array([12, 24, 36])

In [24]:
a == 2

array([False,  True, False])

In [25]:
b > 10

array([False,  True,  True])

In [26]:
(a == 2) & (b > 10)

array([False,  True, False])

- 2차원 배열(행렬)

In [27]:
c = np.array([[1, 2, 3],
              [4, 5, 6]])

In [28]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
c.shape

(2, 3)

In [30]:
# 행의 개수
len(c)

2

In [31]:
# 열의 개수
len(c[0])

3

In [32]:
np.array([[10, 20, 30, 40],
          [50, 60, 70, 80]])

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

- 3차원 배열 (깊이 * 행 * 열)

In [39]:
d = np.array([[[1, 2, 3, 4], 
               [5, 6, 7, 8]],
             [[9, 10, 11, 12], 
              [13, 14, 15, 16]]])
d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [40]:
d.ndim

3

In [41]:
d.shape

(2, 2, 4)

배열의 인덱싱

In [42]:
a = np.array([_ for _ in range(5)])
a

array([0, 1, 2, 3, 4])

In [43]:
a[2]

2

In [44]:
a[-1]

4

In [45]:
a = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [46]:
a[0, :]    # 첫번째 행 전체

array([0, 1, 2, 3])

In [48]:
a[:, 1]    # 두번째 열 전체

array([1, 5])

In [50]:
m = np.array([_ for _ in range(15)]).reshape(3, 5)
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [82]:
# 7 인덱싱
print(m[1,2])
# 14 인덱싱
print(m[-1,-1])
# 6, 7 슬라이싱
print(m[1, 1:3])
# 7, 12 슬라이싱
print(m[1:,2])
# [[3, 4], [8, 9]] 슬라이싱
print(m[:2,3:])

7
14
[6 7]
[ 7 12]
[[3 4]
 [8 9]]


- ndarray 생성 방법

In [83]:
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [86]:
c = np.zeros((5, 2), dtype="i")
c

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int32)

In [88]:
d = np.zeros(5, dtype='U4')
d

array(['', '', '', '', ''], dtype='<U4')

In [89]:
d[0] = "abc"
d[1] = "abcd"
d[2] = "ABCDE" # U4이기 때문에 D에서 짤림
d

array(['abc', 'abcd', 'ABCD', '', ''], dtype='<U4')

In [90]:
e = np.ones((2, 3, 4), dtype="i8")
e

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [91]:
# f를 b와 같은 크기의 배열로 생성
f = np.ones_like(b, dtype="f")
f

array([1., 1., 1.], dtype=float32)

### empty
- 배열을 생성만 하고 특정한 값으로 초기화를 하지 않음   
### arange
- numpy 버전의 range

In [92]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [93]:
np.arange(3, 21, 2)

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

In [94]:
# linspace 선형 구간

np.linspace(0, 100, 5)    # 시작, 끝(포함), 갯수

array([  0.,  25.,  50.,  75., 100.])

In [95]:
# logspace 로그 구간

np.logspace(0, 100, 5) # 시작, 끝(포함), 갯수

array([1.e+000, 1.e+025, 1.e+050, 1.e+075, 1.e+100])

### 연산

In [97]:
A = np.arange(1, 7).reshape(2, 3)
A

array([[1, 2, 3],
       [4, 5, 6]])

In [99]:
# 전치 연산(transpose)
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [100]:
ex3 = np.arange(12)
ex3.reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [101]:
ex3.reshape(4, -1)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [102]:
ex3.reshape(2, 3, -1)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [103]:
ex3.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [104]:
ex3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### 배열 연결

In [105]:
# hstack 명령은 행의 수가 같은 두 개 이상의 배열을 옆으로 연결하여 열의 수가 더 많은 배열을 만듬
a1 = np.ones((2, 3))
a2 = np.zeros((2, 2))
np.hstack([a1, a2])

array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.]])

In [106]:
# vstack 명령은 열의 수가 같은 두 개 이상의 배열을 위 아래로 연결하여 행의 수가 더 많은 배열을 만듬
b1 = np.ones((2, 3))
b2 = np.zeros((3, 3))
np.vstack([b1, b2])

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [107]:
# dstack 명령은 깊이 방향으로 배열을 합친다.
# 가장 안쪽의 원소의 차원이 증가한다.
# shape 정보로 보자면 가장 끝에 값이 2인 차원이 추가되는 것

c1 = np.ones((3, 4))
c1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [108]:
c2 = np.zeros((3, 4))
c2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [109]:
np.dstack([c1, c2])

array([[[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]]])

In [110]:
np.dstack([c1, c2]).shape

(3, 4, 2)

In [111]:
# stack은 dstack의 기능을 확장한 것
# dstack처럼 마지막 차원으로 연결하는 것이 아니라 사용자가 지원한 축으로 배열을 연결
# 연결하고자 하는 배열들의 크기가 모두 같아야함
# axis의 default 값은 0

c = np.stack([c1, c2])
c

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [112]:
c.shape

(2, 3, 4)

In [113]:
c = np.stack([c1, c2], axis=1)
c

array([[[1., 1., 1., 1.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.]]])

In [114]:
c.shape

(3, 2, 4)

In [115]:
# r 메서드는 hstack과 비슷하게 배열을 좌우로 연결한다
# 메서드임에도 불구하고 []를 사용함
# 이러한 특수 메서드를 인덱서라고 한다.

np.r_[np.array([1, 2, 3]), np.array([4, 5, 6])]

array([1, 2, 3, 4, 5, 6])

In [116]:
# c 메서드는 배열의 차원을 증가시킨 후 좌우로 연결한다.
# 1차원 배열을 연결하면 2차원 배열이 된다.

np.c_[np.array([1, 2, 3]), np.array([4, 5, 6])]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [117]:
# tile 명령은 동일한 배열을 반복하여 연결

a = np.array([[0, 1, 2], [3, 4, 5]])
np.tile(a, 2)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [118]:
np.tile(a, (3, 2))

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [120]:
tmp = np.zeros(9)
tmp

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [122]:
tmp = tmp.reshape(3, 3)
tmp

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [124]:
tmp1 = np.ones(6)
tmp1

array([1., 1., 1., 1., 1., 1.])

In [126]:
tmp1 = tmp1.reshape(3, 2)
tmp1

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [128]:
tmp = np.hstack([tmp, tmp1])
tmp

array([[0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 1.]])

In [130]:
tmp2 = np.arange(10, 151, 10, dtype='f').reshape(3, 5)
tmp2

array([[ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]], dtype=float32)

In [131]:
tmp = np.vstack([tmp, tmp2])
tmp

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

In [135]:
tmp = np.tile(tmp, (2, 1))
tmp

array([], shape=(96, 0), dtype=float64)

In [141]:
tmp = np.zeros((3, 3))
tmp1 = np.ones((3, 2))
tmp = np.hstack([tmp, tmp1])
tmp2 = np.arange(10, 151, 10, dtype='f').reshape(3, 5)
tmp = np.vstack([tmp, tmp2])
tmp = np.tile(tmp, (2, 1))
tmp

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

### 벡터화 연산

In [2]:
import numpy as np

x = np.arange(1, 10001)
y = np.arange(10001, 20001)

In [11]:
%%time
z = x + y

CPU times: user 28 µs, sys: 4 µs, total: 32 µs
Wall time: 29.8 µs


In [12]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
c = np.array([1, 2, 3, 4])

In [13]:
a == b

array([False,  True, False,  True])

In [14]:
a == c

array([ True,  True,  True,  True])

In [15]:
np.all(a == b)

False

In [16]:
np.all(a == c)

True

In [17]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
100 * x

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [19]:
x = np.arange(12).reshape(3, 4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [20]:
100 * x

array([[   0,  100,  200,  300],
       [ 400,  500,  600,  700],
       [ 800,  900, 1000, 1100]])

## 차원 축소 연산
- 최대/최소: min, max, argmin, argmax
- 통계: sum, mean, median, std, var
- 불리언: all, any

In [21]:
# sum 해당 배열의 합산 결과를 반환
# 2차원 이상일 때에는 axis 키워드 인수를 사용할 수 있다.

x = np.array([1, 2, 3, 4])
np.sum(x)

10

In [22]:
x = np.arange(12).reshape(3, -1)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [23]:
x.sum(axis=0)

array([12, 15, 18, 21])

In [24]:
x.sum(axis=1)

array([ 6, 22, 38])

In [25]:
# min 메서드는 해당 배열의 제일 작은 값의 결과를 반환
# 연산 대상이 2차원 이상일 때에는 axis 키워드 인수를 사용할 수 있다.
x = np.arange(20).reshape(2, 5, -1)
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [26]:
x.min()

0

In [27]:
x.min(axis=0)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [28]:
np.min(x, axis=1)

array([[ 0,  1],
       [10, 11]])

In [30]:
x.min(axis=2)

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [31]:
# argmin() 해당 배열의 제일 작은 값의 인덱스르 ㄹ반환
# 연산 대상이 2차원 이상일 때에는 axis 키워드 인수를 사용할 수 있다.

x.argmin(axis=0)

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [32]:
np.argmin(x, axis=1)

array([[0, 0],
       [0, 0]])

In [33]:
x.argmin(axis=2)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [34]:
# max 메서드는 해당 배열의 제일 큰 값의 결과를 반환
# 연산 대상이 2차원 이상일 때에는 axis 키워드 인수를 사용할 수 있다.

x.max(axis=0)

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [35]:
np.max(x, axis=1)

array([[ 8,  9],
       [18, 19]])

In [36]:
x.max(axis=2)

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [37]:
# argmax 메서드는 해당 배열의 제일 큰 값의 인덱스를 반환
# 2차원 이상일 때에는 axis 키워드 인수를 사용할 수 있다.
x.argmax()

19

In [38]:
np.argmax(x)

19

In [39]:
x.argmax(axis=0)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [40]:
np.argmax(x, axis=1)

array([[4, 4],
       [4, 4]])

In [41]:
x.argmax(axis=2)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [46]:
# mean 평균
x.mean()
# median 중앙값
np.median(x)
# all 모든 요소가 True일때 True
# any는 하나라도 True면 True

9.5

In [47]:
practice = np.array([[1.1, 7.1, 8.0, 2.1, 6.5, 7.2],
                     [2.7, 5.2, 3.3, 9.0, 7.7, 2.8],
                     [0.7, 8.8, 4.2, 8.9, 4.3, 7.4],
                     [8.2, 1.1, 5.4, 2.9, 6.9, 0.2],
                     [7.4, 4.8, 2.7, 3.1, 2.8, 8.9]])

In [50]:
practice.shape

(5, 6)

In [48]:
np.max(practice)

9.0

In [63]:
np.sum(practice, axis=1)

array([32. , 30.7, 34.3, 24.7, 29.7])

In [64]:
np.max(practice, axis=1)

array([8. , 9. , 8.9, 8.2, 8.9])

In [65]:
np.mean(practice, axis=0)

array([4.02, 5.4 , 4.72, 5.2 , 5.64, 5.3 ])

In [69]:
np.min(practice, axis=0)

array([0.7, 1.1, 2.7, 2.1, 2.8, 0.2])

In [79]:
practice = np.array([[1.1, 7.1, 8.0, 2.1, 6.5, 7.2],
                     [2.7, 5.2, 3.3, 9.0, 7.7, 2.8],
                     [0.7, 8.8, 4.2, 8.9, 4.3, 7.4],
                     [8.2, 1.1, 5.4, 2.9, 6.9, 0.2],
                     [7.4, 4.8, 2.7, 3.1, 2.8, 8.9]])

# shape 확인
print("shape =", practice.shape)
# 1
print("전체의 최댓값 =", np.max(practice))
# 2
print("각 행의 합 =", np.sum(practice, axis=1))
# 3
print("각 행의 최댓값 =", np.max(practice, axis=1))
# 4
print("각 열의 평균 =", np.mean(practice, axis=0))
# 5
print("각 열의 최솟값 =",np.min(practice, axis=0))

shape = (5, 6)
전체의 최댓값 = 9.0
각 행의 합 = [32.  30.7 34.3 24.7 29.7]
각 행의 최댓값 = [8.  9.  8.9 8.2 8.9]
각 열의 평균 = [4.02 5.4  4.72 5.2  5.64 5.3 ]
각 열의 최솟값 = [0.7 1.1 2.7 2.1 2.8 0.2]


In [80]:
# 정렬
# a.sort()
# 자료를 정렬하는것이 아니라 순서만 알고 싶다면 argsort
a = np.array([42, 38, 12, 25])
j = np.argsort(a)
j

array([2, 3, 1, 0])

In [81]:
a[j]

array([12, 25, 38, 42])

In [83]:
a = np.arange(1, 7).reshape(3, 2)
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [84]:
a[[0, 1, 2], [0, 1, 0]]

array([1, 4, 5])

In [108]:
scores = np.array([[1, 2, 3, 4],
                   [46, 99, 100, 71],
                   [81, 59, 90, 100]])
tmp = np.argsort(scores[1])    # 2번째 줄을 argsort한 인덱스 값이 tmp에 저장됨
for i in range(0, 3):
    scores[i] = scores[i][tmp]
scores

array([[  1,   4,   2,   3],
       [ 46,  71,  99, 100],
       [ 81, 100,  59,  90]])

## 난수 생성

In [109]:
np.random.seed(0)

In [110]:
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [111]:
np.random.rand(10)

array([0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152,
       0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606])

In [112]:
np.random.rand(10)

array([0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215,
       0.97861834, 0.79915856, 0.46147936, 0.78052918, 0.11827443])

In [113]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [115]:
np.random.shuffle(x)
x

array([5, 7, 6, 1, 9, 3, 0, 2, 8, 4])

In [127]:
# 0부터 1 사이의 균일 분포
np.random.rand(10)

array([0.89603839, 0.63892108, 0.89155444, 0.68005557, 0.44919774,
       0.97857093, 0.11620191, 0.7670237 , 0.41182014, 0.67543908])

In [128]:
np.random.rand(3, 5)

array([[0.24979628, 0.31321833, 0.96541622, 0.58846509, 0.65966841],
       [0.53320625, 0.23053302, 0.39486929, 0.61880856, 0.47486752],
       [0.47013219, 0.71607453, 0.287991  , 0.38346223, 0.74916984]])

In [129]:
# randn 기댓값(mean)이 0이고 표준편차가 1인 표준 정규 분포를 따르는 난수 생성
np.random.randn(10)

array([-0.25579069, -0.71438561, -0.50083877,  0.05564534, -0.48896178,
       -0.37992245,  0.25973465, -1.68134864, -0.91679481, -0.1192241 ])

In [130]:
np.random.randn(3, 5)

array([[-0.44627728, -2.14335544,  0.01003777, -0.55822259,  0.48090565],
       [-0.57414201, -0.2524676 ,  1.03984679, -0.02347953,  0.08942229],
       [-0.59432737, -0.10569679,  0.74279571, -0.75498153, -0.13828271]])

In [131]:
# randint 함수는 다음과 같은 인수를 가짐
# numpy.random.randint(low, high=None, size=None)
# high를 입력하지 않으면 0과 low사이의 숫자를, high를 입력하면 low와 high 사이의 숫자를 출력

np.random.randint(10, size=10)


array([5, 8, 4, 0, 2, 5, 5, 0, 8, 1])

In [132]:
np.random.randint(10, 20, size=10)

array([11, 10, 13, 18, 18, 14, 14, 10, 19, 13])

In [133]:
np.random.randint(10, 40, (3, 5))

array([[17, 38, 13, 28, 39],
       [27, 11, 28, 27, 39],
       [30, 39, 12, 15, 15]])

## 데이터 샘플링
numpy.random.choice(a, size=None, replace=True, p=None)
- a : 배열이면 원래의 데이터, 정수이면 arange(a) 명령으로 데이터 생성
- size : 정수, 샘플 숫자
- replace : 불리언, True이면 한 번 선택한 데이터를 다시 선택 가능
- p : 배열, 각 데이터가 선택될 수 있는 확률

In [121]:
np.random.choice(5, 5, replace=False)    # 셔플과 같다.

array([0, 1, 2, 3, 4])

In [122]:
np.random.choice(5, 3, replace=False)    # 3개만 선택

array([4, 2, 3])

In [123]:
np.random.choice(5, 10)    # 반복해서 10개 선택

array([3, 0, 0, 1, 2, 4, 2, 0, 3, 2])

In [124]:
np.random.choice(5, 10, p=[0.1, 0, 0.3, 0.6, 0])    # 선택 확률을 다르게 해서 선택

array([3, 0, 3, 0, 3, 3, 2, 3, 3, 3])

In [144]:
# 동전 앞면 확률
np.random.seed(0)
tmp = np.random.randint(2, size=100)
print(np.count_nonzero(tmp) / 100)


0.56


In [146]:
# 주사위 확률
np.random.seed(0)
res = np.random.randint(1, 7, size=100)
np.sum(res) / len(res)
# res.mean() 도 같은 결과!

3.42

## 정수 데이터 카운팅
- unique
- bincount

In [149]:
# unique 중복된 값을 제거하고 중복되지 않는 값의 리스트를 출력
# return_counts 인수를 True로 설정하면 각 값의 데이터의 개수도 출력
np.unique([11, 11, 2, 2, 34, 34])
np.unique([11, 11, 2, 2, 34, 34], return_counts=True)

(array([ 2, 11, 34]), array([2, 2, 2]))

In [150]:
# unique는 데이터가 하나도 없는 경우에는 정보를 주지 않음
# 주사위를 던졌을 때 처럼 특정 범위 안의 수인 경우에는 bincount 함수에 min/length 인수를 설정하는 것이 편하다.
# bincount 함수는 0부터 minlength -1 까지의 숫자에 대해 각각 카운트를 한다.
np.bincount([1, 1, 2, 2, 2, 3], minlength=6)

array([0, 2, 3, 1, 0, 0])